### ISSUE TITLE
Transfer review on second mapping

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/diveboard-data-publication#12]
Hi @DimEvil ,

I reviewed the DwC file you gave me and updated the status on the [Darwin Core mapping file](https://github.com/Datafable/diveboard-gbif/blob/master/standardization/dwc-mapping.md).
- `OK`: Looks great, no change needed.
- `change`: Change required. I added an explanation.
- `remove`: This field can be removed from mapping.
- `empty`: Is in the output, but currently still empty for all fields.
- `suggested`: Might be interesting to add.
- `-`: Not necessary.

I also made two changes to the dataset on IPT:
1. Reverted back to private
2. Stopped daily publication (this would increase the version number). If necessary, we can add monthly republication later.

Can you transfer this info to the Diveboard crew? You can link to the file above. Let me know if you have questions or other opinions. You can close this issue once finished.

Peter

PS: As the name for the dataset, I suggest:

> Diveboard - Scuba diving citizen science

**Comment by peterdesmet** [comment]
Or: Diveboard - Scuba diving citizen science observations

**Comment by peterdesmet** [comment]
Also, awesome work by Diveboard so far!

**Comment by DimEvil** [comment]
Gek, ik had dat al op private gezet...

**Comment by DimEvil** [comment]
diveboard: 7_0_33102
Dat nummerke is een interne ID, maar om het globally unique te maken staat
er "diveboard: " voor.

**Comment by DimEvil** [comment]
aha, da stond op daily publication.... das iets van Alex :P

**Comment by peterdesmet** [comment]
'k Weet niet of Alex dat op daily en publiek gezet had.

**Comment by peterdesmet** [comment]
What is the origin of `7_0_33102` (internal ID) and `20745099` (catalogNumber)?
Wouldn't it be better to use `diveboard:20745099` and keep the internal ID hidden?

**Comment by DimEvil** [comment]
Maybe another solution. But why should the record ID be hidden? We can not
use catalogNumber, as it is totally wrong... There are species ID's in that
column. Working on a fix!
