### ISSUE TITLE
Data hosting

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/diveboard-data-publication#2]
Which platform will we use to host the published data (IPT?) and who will manage this?

cc @DimEvil

**Comment by DimEvil** [comment]
Option 1: ipt.biodiversity.be 
Option 2: Is there a public IPT hosted by GBIF for such cases?
Option 3: Ipt of INBO (might not be the best solution)
Option 4: Can we host a new IPT with Datafable... (Probably not really needed...)

@Datafable/owners

**Comment by peterdesmet** [comment]
ipt.biodiversity.be is probably the most pragmatic solution, but there are several aspects to consider:
1. Access to IPT by Diveboard admins
2. Access to IPT by us
3. Endorsement by an official GBIF (national) node.

Where is Diveboard based?

**Comment by DimEvil** [comment]
- ipt.biodiversity.be is already endorsed by the Belgian node!
- Access could be granted (theoretically by the biodiversity.be admins @niconoe )
- Only @peterdesmet needs an extra account on ipt.biodiversity.be (I don t think it s an issue) @niconoe @silenius and me already have an account there...

I don t think it s the best option, but feasible. Off course, the diveboard can host there own IPT, off course, then they need endorsement from (probably) the national node (or maybe directly through GBIF). I don't think this will bring any problems... 
"Diveboard" is based in France, Paris area!, so they can 'if needed' connect with GBIF France...

**Comment by peterdesmet** [comment]
1. Ask GBIF France if they can endorse Diveboard as an organization.
2. (optional) Ask GBIF France if they have a national IPT that can host the data.

**Comment by DimEvil** [comment]
1. I ll do that in a later stage...
2. I'm not sure of this.... depends a little on how stuff is going? for me both options are still open; either on the France  (less control by us) or on the Belgian IPT (probably more control by us)

**Comment by peterdesmet** [comment]
Diveboard decided to host their [own ipt](http://ipt.diveboard.com). The organization is endorsed by France.
