### ISSUE TITLE
How to map location information?

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/diveboard-data-publication#5]
Next to the coordinates, 4 values are recorded for Dive site:

```
1. Country: Spain                          dwc:country
2. Location: Estartit & Medes Islands      dwc:locality?
3. Spot Name: Cavell Bernat                dwc:locality
4. Sea / Lake Name: Mediterranean Sea      dwc:waterBody
```

There are also 2 IDs, which I guess refer to 2) Location and 3) Spot name

```
2. <Region:0x00000006498760>      dwc:higherGeographyID?
3. <Location:0x000000068d9c98>    dwc:locationID
```

`Country` and `Sea / Lake Name` are easy to map and  `dwc:locality` should contain the most specific description, so this term should at least contain `Spot Name`. The question is how to map `Location`?
1. As part of the locality, separated by comma: `Cavell Bernat, Estartit & Medes Islands`. In this case, we should not map the related `<region:id>`.
2. In one of the atomic fields `stateProvince`, `island`, `islandGroup`, etc. based on the content. This is difficult to do.
3. As part of higherGeography, together with `Country` and maybe `Sea / Lake Name`: `Spain; Estartit & Medes Islands`. That way we could map `<region:id>`.

My preferred option is option 1, as it is the most readable in my opinion, but I could be convinced of option 3. cc @DimEvil

**Comment by DimEvil** [comment]
Spot name is "dwc: locality"
Country is "dwc: country"
Sea/ lake name is dwc: waterbody

Location: not defined enough, can be dwc: island group, but also can be something totally different. (I would skip this term)

**Comment by peterdesmet** [comment]
I think we need to have some more actual data to review if we drop or include this.

**Comment by DimEvil** [comment]
I m not sure.... I think we have enough with locality; country & waterbody  & lat/long 
These field perfectly indicate the spot..., not?

**Comment by peterdesmet** [comment]
Decided on:
- dwc:country: Country
- dwc:countryCode
- dwc:waterbody
- dwc:locality: Divespot
- dwc:verbatimLocality: Divespot, Region, e.g. Cavell Bernat, Estartit & Medes Islands

We won't use:
- dwc:locationID, dwc:higherGeographyID: no internal IDs
- dwc:stateOrProvince, dwc:county: no info
- dwc:municipality: region is a mix of levels, better to use in verbatimLocality
