### ISSUE TITLE
Values for MeasurementOrFact extension

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/diveboard-data-publication#6]
There are some **useful** physical data available that do not fit in the `dwc:occurrence` core, but could be provided in the `MeasurementOrFact` extension. These are:
- [ ] Surface temperature
- [ ] Bottom temperature
- [ ] Water visibility
- [ ] Current
- [ ] Water type

It needs to be determined which ones we include. If we only include 1 or 2 fields, `dynamicProperties` can be used as well, in the format:

```
 surfaceTemperatureInDegreesCelsius=20.0,waterVisibilityRangeInMeters=10-25
```

cc @DimEvil

**Comment by DimEvil** [comment]
This makes sence! But, in reality, divers don t record these parameters. And they will not add to much to the "value" of the recordings.

Example: I never recorded (in the past) these parameters in my divers log,  We could suggest this to diveboard, but I think the added value is reasonable "Low"

**Comment by peterdesmet** [comment]
We need more data to check if these terms are often populated or not.

**Comment by peterdesmet** [comment]
Decided not to implement this.
