### ISSUE TITLE
Indicate citizen science in data

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/diveboard-data-publication#9]
We need to communicate to the user that these data are originated by citizen science. We definitely have to do this in the metadata, but it is useful to indicate this on record level as well.

Option 1 (see also [ABCD](http://wiki.tdwg.org/twiki/bin/view/ABCD/AbcdConcept0398)):

```
identificationVerificationStatus: 0
samplingProtocol: ad hoc observation
```

Option 2

```
(identificationVerificationStatus: 0)
samplingProtocol: citizen science observation
```

**Comment by DimEvil** [comment]
My preference goes to option 2
